
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/sunny/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Linux - 6.11.0-21-generic - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/home/sunny/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/home/sunny/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/home/sunny/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.30/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: /usr/bin/clang++-15 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      /usr/bin/ld: cannot find -lstdc++: No such file or directory
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/home/sunny/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/home/sunny/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/home/sunny/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.30/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /usr/bin/clang++-15 
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.o"
      
      The CXX compiler identification is Clang, found in:
        /home/sunny/work/TachosDB/cmake-build-release/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.o
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/home/sunny/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.30/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "/home/sunny/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.30/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "/home/sunny/work/TachosDB/cmake-build-release/CMakeFiles/CMakeScratch/TryCompile-kLgDpc"
      binary: "/home/sunny/work/TachosDB/cmake-build-release/CMakeFiles/CMakeScratch/TryCompile-kLgDpc"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_SCAN_FOR_MODULES: "OFF"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/home/sunny/work/TachosDB/cmake-build-release/CMakeFiles/CMakeScratch/TryCompile-kLgDpc'
        
        Run Build Command(s): /home/sunny/.local/share/JetBrains/Toolbox/apps/clion/bin/ninja/linux/x64/ninja -v cmTC_ecd8a
        [1/2] /usr/bin/clang++-15   -fcolor-diagnostics   -v -MD -MT CMakeFiles/cmTC_ecd8a.dir/CMakeCXXCompilerABI.cpp.o -MF CMakeFiles/cmTC_ecd8a.dir/CMakeCXXCompilerABI.cpp.o.d -o CMakeFiles/cmTC_ecd8a.dir/CMakeCXXCompilerABI.cpp.o -c /home/sunny/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.30/Modules/CMakeCXXCompilerABI.cpp
        Ubuntu clang version 15.0.7
        Target: x86_64-pc-linux-gnu
        Thread model: posix
        InstalledDir: /usr/bin
        Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/12
        Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/13
        Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/14
        Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/14
        Candidate multilib: .;@m64
        Selected multilib: .;@m64
         (in-process)
         "/usr/lib/llvm-15/bin/clang" -cc1 -triple x86_64-pc-linux-gnu -emit-obj -mrelax-all --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCXXCompilerABI.cpp -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -v -fcoverage-compilation-dir=/home/sunny/work/TachosDB/cmake-build-release/CMakeFiles/CMakeScratch/TryCompile-kLgDpc -resource-dir /usr/lib/llvm-15/lib/clang/15.0.7 -dependency-file CMakeFiles/cmTC_ecd8a.dir/CMakeCXXCompilerABI.cpp.o.d -MT CMakeFiles/cmTC_ecd8a.dir/CMakeCXXCompilerABI.cpp.o -sys-header-deps -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++ -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/x86_64-linux-gnu -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/backward -internal-isystem /usr/lib/llvm-15/lib/clang/15.0.7/include -internal-isystem /usr/local/include -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir=/home/sunny/work/TachosDB/cmake-build-release/CMakeFiles/CMakeScratch/TryCompile-kLgDpc -ferror-limit 19 -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fcolor-diagnostics -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o CMakeFiles/cmTC_ecd8a.dir/CMakeCXXCompilerABI.cpp.o -x c++ /home/sunny/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.30/Modules/CMakeCXXCompilerABI.cpp
        clang -cc1 version 15.0.7 based upon LLVM 15.0.7 default target x86_64-pc-linux-gnu
        ignoring nonexistent directory "/usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/x86_64-linux-gnu"
        ignoring nonexistent directory "/usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/backward"
        ignoring nonexistent directory "/usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../x86_64-linux-gnu/include"
        ignoring nonexistent directory "/include"
        #include "..." search starts here:
        #include <...> search starts here:
         /usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++
         /usr/lib/llvm-15/lib/clang/15.0.7/include
         /usr/local/include
         /usr/include/x86_64-linux-gnu
         /usr/include
        End of search list.
        [2/2] : && /usr/bin/clang++-15  -v -Wl,-v CMakeFiles/cmTC_ecd8a.dir/CMakeCXXCompilerABI.cpp.o -o cmTC_ecd8a   && :
        FAILED: cmTC_ecd8a 
        : && /usr/bin/clang++-15  -v -Wl,-v CMakeFiles/cmTC_ecd8a.dir/CMakeCXXCompilerABI.cpp.o -o cmTC_ecd8a   && :
        Ubuntu clang version 15.0.7
        Target: x86_64-pc-linux-gnu
        Thread model: posix
        InstalledDir: /usr/bin
        Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/12
        Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/13
        Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/14
        Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/14
        Candidate multilib: .;@m64
        Selected multilib: .;@m64
         "/usr/bin/ld" -pie --build-id --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o cmTC_ecd8a /lib/x86_64-linux-gnu/Scrt1.o /lib/x86_64-linux-gnu/crti.o /usr/bin/../lib/gcc/x86_64-linux-gnu/14/crtbeginS.o -L/usr/bin/../lib/gcc/x86_64-linux-gnu/14 -L/usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -L/usr/lib/llvm-15/bin/../lib -L/lib -L/usr/lib -v CMakeFiles/cmTC_ecd8a.dir/CMakeCXXCompilerABI.cpp.o -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/bin/../lib/gcc/x86_64-linux-gnu/14/crtendS.o /lib/x86_64-linux-gnu/crtn.o
        GNU ld (GNU Binutils for Ubuntu) 2.42
        /usr/bin/ld: cannot find -lstdc++: No such file or directory
        clang: error: linker command failed with exit code 1 (use -v to see invocation)
        ninja: build stopped: subcommand failed.
        
      exitCode: 1
  -
    kind: "try_compile-v1"
    backtrace:
      - "/home/sunny/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.30/Modules/CMakeTestCXXCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Check for working CXX compiler: /usr/bin/clang++-15"
    directories:
      source: "/home/sunny/work/TachosDB/cmake-build-release/CMakeFiles/CMakeScratch/TryCompile-hSiksr"
      binary: "/home/sunny/work/TachosDB/cmake-build-release/CMakeFiles/CMakeScratch/TryCompile-hSiksr"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_SCAN_FOR_MODULES: "OFF"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_CXX_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: '/home/sunny/work/TachosDB/cmake-build-release/CMakeFiles/CMakeScratch/TryCompile-hSiksr'
        
        Run Build Command(s): /home/sunny/.local/share/JetBrains/Toolbox/apps/clion/bin/ninja/linux/x64/ninja -v cmTC_77c39
        [1/2] /usr/bin/clang++-15   -fcolor-diagnostics -MD -MT CMakeFiles/cmTC_77c39.dir/testCXXCompiler.cxx.o -MF CMakeFiles/cmTC_77c39.dir/testCXXCompiler.cxx.o.d -o CMakeFiles/cmTC_77c39.dir/testCXXCompiler.cxx.o -c /home/sunny/work/TachosDB/cmake-build-release/CMakeFiles/CMakeScratch/TryCompile-hSiksr/testCXXCompiler.cxx
        [2/2] : && /usr/bin/clang++-15   CMakeFiles/cmTC_77c39.dir/testCXXCompiler.cxx.o -o cmTC_77c39   && :
        FAILED: cmTC_77c39 
        : && /usr/bin/clang++-15   CMakeFiles/cmTC_77c39.dir/testCXXCompiler.cxx.o -o cmTC_77c39   && :
        /usr/bin/ld: cannot find -lstdc++: No such file or directory
        clang: error: linker command failed with exit code 1 (use -v to see invocation)
        ninja: build stopped: subcommand failed.
        
      exitCode: 1
...
