#!/bin/bash

unset VFENGINE_AMAZON0601_DATASET_PATH
unset VFENGINE_AMAZON0601_SERIALIZED_READ_PATH
unset VFENGINE_AMAZON0601_SERIALIZED_WRITE_PATH
unset VFENGINE_ENABLE_HOT_RUN
unset VFENGINE_ENABLE_COLD_RUN
unset VFENGINE_DISABLE_SERIALIZE
unset VFENGINE_DISABLE_DESERIALIZE

echo "VFENGINE_AMAZON0601_DATASET_PATH is unset to: $VFENGINE_AMAZON0601_DATASET_PATH"
echo "VFENGINE_AMAZON0601_SERIALIZED_READ_PATH is unset to: $VFENGINE_AMAZON0601_SERIALIZED_READ_PATH"
echo "VFENGINE_AMAZON0601_SERIALIZED_WRITE_PATH is unset to: $VFENGINE_AMAZON0601_SERIALIZED_WRITE_PATH"
echo "VFENGINE_ENABLE_HOT_RUN is unset to: $VFENGINE_ENABLE_HOT_RUN"
echo "VFENGINE_ENABLE_COLD_RUN is unset to: $VFENGINE_ENABLE_COLD_RUN"
echo "VFENGINE_DISABLE_SERIALIZE is unset to: $VFENGINE_DISABLE_SERIALIZE"
echo "VFENGINE_DISABLE_DESERIALIZE is unset to: $VFENGINE_DISABLE_DESERIALIZE"

#This script returns the environment to the original state before engine was run